# Module manifest for module 'EPV_API_Common'
# Generated by: Brian Andrew Bors
# Generated on: 2024-06-07
@{
    # Script module or binary module file associated with this manifest.
    RootModule           = 'EPV-API-Common.psm1'

    # Version number of this module.
    ModuleVersion        = '0.1.1'

    # ID used to uniquely identify this module
    GUID                 = '42f9f4c6-bb1a-465a-9276-214b28f0e297'

    # Author of this module
    Author               = 'Brian Andrew Bors'

    # Company or vendor of this module
    CompanyName          = 'CyberArk'

    # Copyright statement for this module
    # Copyright         = ''

    # Description of the functionality provided by this module
    Description          = 'Common Functions used on EPV-API-Scripts'

    # Private data available to the module
    PrivateData          = @{
        # Additional metadata used by PowerShellGet for publishing
        PSData = @{
            # Prerelease string should be here, so ModuleBuilder can set it
            Prerelease               = ''

            # Release Notes have to be here, so ModuleBuilder can update them
            ReleaseNotes             = ''

            # Tags applied to this module in online galleries.
            Tags                     = @()

            # A URL to the license for this module.
            # LicenseUri = ''

            # A URL to the main website for this project.
            # ProjectUri = ''

            # A URL to an icon representing this module.
            # IconUri = ''

            # Flag to indicate whether the module requires explicit user acceptance for install/update/save
            RequireLicenseAcceptance = $false

            # Modules that are in RequiredModules which don't need to be installed by PowerShellGet
            # ExternalModuleDependencies = @()

        } # End of PSData hashtable

    } # End of PrivateData hashtable

    # Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
    FunctionsToExport    = @('Get-DirectoryService','Add-IdentityRoleToUser','Get-IdentityGroup','Get-IdentityRole','Get-IdentityRoleInDir','Get-IdentityRoleMember','New-IdentityRole','Remove-IdentityRole','Remove-IdentityRoleFromUser','Get-IdentityUser','Remove-IdentityUser','Add-AccountGroup','Add-AccountGroupMember','Get-AccountGroup','Get-AccountGroupMember','Remove-AccountGroup','Add-Account','Get-Account','Get-AccountLink','Set-Account','Set-AccountLink','Export-Safe','Get-Safe','New-Safe','Set-Safe','Add-SafeMember','Export-SafeMember','Get-SafeMember','Remove-SafeMember','Set-SafeMember','Get-CPMUser','Get-SystemHealth','Add-TestVaultUser','Get-VaultUser','Remove-VaultUser','Add-BaseQueryParameter','New-Session','Write-LogMessage - orginal','Write-LogMessage')

    # Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
    CmdletsToExport      = @()

    # Variables to export from this module
    VariablesToExport    = @()

    # Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
    AliasesToExport      = @()

    # DSC resources to export from this module
    # DscResourcesToExport = @()

    # Modules that must be imported into the global environment prior to importing this module
    # RequiredModules = @()

    # Assemblies that must be loaded prior to importing this module
    RequiredAssemblies = @()

    # Script files (.ps1) that are run in the caller's environment prior to importing this module.
    #ScriptsToProcess = @()

    # Type files (.ps1xml) to be loaded when importing this module
    # TypesToProcess = @()

    # Format files (.ps1xml) to be loaded when importing this module
    FormatsToProcess     = @(".\Format\SafeMember", ".\Format\Safe")

    # Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
    NestedModules        = @(".\Modules\IdentityAuth.psm1")

    # List of all modules packaged with this module
    ModuleList           = @(".\Modules\IdentityAuth.psm1")

    # List of all files packaged with this module
    FileList             = @()

    # HelpInfo URI of this module
    # HelpInfoURI = ''

    # Supported PSEditions
    # CompatiblePSEditions = @()

    # Minimum version of the Windows PowerShell engine required by this module
    PowerShellVersion    =  "6.0"

    # Name of the Windows PowerShell host required by this module
    # PowerShellHostName = ''

    # Minimum version of the Windows PowerShell host required by this module
    # PowerShellHostVersion = ''

    # Minimum version of Microsoft .NET Framework required by this module.
    # This prerequisite is valid for the PowerShell Desktop edition only.
    # DotNetFrameworkVersion = ''

    # Minimum version of the common language runtime (CLR) required by this module.
    # This prerequisite is valid for the PowerShell Desktop edition only.
    # CLRVersion = ''

    # Processor architecture (None, X86, Amd64) required by this module
    # ProcessorArchitecture = ''

    # Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
    # DefaultCommandPrefix = ''

}
